### ISSUE TITLE
Delayed Address Change

### ISSUE THREAD

**Issue by Agonyxxx** [3022-2/raccoon_clipper#2]
so when i copy an an address it take like 1 or 2 seconds to change it to my address so if someone is fast enough to copy paste he will get his address and not mine maybe it's because the sleep time ?

**Comment by 3022-2** [comment]
Sleep time is.25 on all methods 


What's your hardware as that's the only way I know at the moment that slows it down

Also try some of the other methods too see if it keeps happening

**Comment by Agonyxxx** [comment]
i tried it on appfly vps and it was delayed it tried it with js script as a exec function and it was instant

**Comment by 3022-2** [comment]
What method were you using ?

**Comment by Agonyxxx** [comment]
first method (best one)

**Comment by 3022-2** [comment]
Would be an issue of hardware

Subprocess uses powershell commands running one after another

- one to get clipboard

If the clipboard is a address

- one to set the new clipboard

Ctypes uses Ctypes to retrieve the clipboard but powershell to set

And Pyperclip uses Pyperclip library for it

In short i don't think it's an issue of code it's an issue of hardware - older computers / worse hardware computers will have a harder time doing doing it fast 

My pc and other pc's I have tried I have been instant 

When I tried with my laptop (Subprocess method) it was slower with 1-2s delay due to the hardware aspect

I will add more methods I think at some point to address this issue and have it instantly read and update

**Comment by Agonyxxx** [comment]
Great dev , Respect

**Comment by 3022-2** [comment]
yo @Agonyxxx i have finished making a new method - faster on old/shitty hardware + all standard library. will release soon with after i add some other optional features

**Comment by Agonyxxx** [comment]
as u said GOAT

**Comment by 3022-2** [comment]
released.

**Comment by Agonyxxx** [comment]
Problems : when you reset config it turns into red in the address box 
2nd it doesn't build 
3rd everytime you reset a config it fully bugs and stops working

**Comment by Agonyxxx** [comment]
Update : to be clear there was an issue on my end in the pyinstaller but however it still goes red when u reset config so the build is fine but if u reset config it turns red

**Comment by Agonyxxx** [comment]
Update : Tested Works as a charm Good Job !

**Comment by 3022-2** [comment]
Weird with the reset - I'll look into it

For now just exit the program and re open

**Comment by 3022-2** [comment]
changed the reset method to a simpler way - should be fixed
